#version: "3.8"
services:
  db:
#    image: postgres:16
    container_name: db
    build: ./db
#    user: "1000:1000"
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
#    networks:
#      - demo-net

  backend:
    container_name: backend
    build:
      context: ./backend
    image: backend:latest
#    user: "1000:1000"
    environment:
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    ports:
      - "8082:8082"
    depends_on:
      - db
    volumes:
      - ~/.gradle:/home/gradle/.gradle
      - ./backend:/app
#    networks:
#      - demo-net
    entrypoint: ["java", "-jar", "/app/build/libs/app-0.0.1-SNAPSHOT.jar"]

  frontend:
    container_name: frontend
    build: ./frontend
    user: "1000:1000"
    ports:
      - "5173:80"
#    networks:
#      - demo-net
    depends_on:
      - backend

volumes:
  db_data:

#networks:
#  demo-net:
#    driver: bridge