#version: "3.8"
services:
  db:
#    image: postgres:16
    container_name: db
    build: ./db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: ./backend
    environment:
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ~/.gradle:/home/gradle/.gradle
      - ./backend:/app

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data: